uploadutils.py: use input() instead of raw_input() for Python3
Fixes this error during upload:
Continue? [y/N] Traceback (most recent call last):
  File "ompi-scripts/dist/upload-release-to-s3.py", line 132, in <module>
    uploadutils.upload_files(s3_client, bucket_name, key_prefix,
  File "/home/bgoglin/ompi-scripts/dist/uploadutils.py", line 228, in upload_files
    if not __query_yes_no('Continue?', 'no'):
  File "/home/bgoglin/ompi-scripts/dist/uploadutils.py", line 74, in __query_yes_no
    choice = raw_input().lower()
NameError: name 'raw_input' is not defined

Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>